version: '2'

services:
  membersrvc:
    image: hyperledger/fabric-membersrvc:x86_64-0.6.1-preview
    hostname: membersrvc
    ports:
      - "7054:7054"
    environment:
      - CORE_LOGGING_SERVER=debug
      - MEMBERSRVC_CA_ACA_ENABLED=true
      - MEMBERSRVC_LOGGING_LEVEL=DEBUG
  #  volumes:
  #    - ./blockchain/membersrvc.yaml:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc/membersrvc.0.6.yaml
    command: membersrvc

  vp0:
    extends:
      file: compose-defaults.yml
      service: vp
    hostname: vp0
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    environment:
      - CORE_PEER_ID=vp0
      - CORE_PEER_DISCOVERY_PERIOD=1s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=1s
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    links:
      - membersrvc

  # blockchain-explorer
  explorer:
    extends:
      file: explorer.yml
      service: explorer
    hostname: explorer
    environment:
      - HYP_REST_ENDPOINT=http://vp0:7050
    ports:
      - "9090:9090"

#explorer:
#  extends:
#    file: explorer.yml
#    service: explorer
#  hostname: explorer
#  environment:
#    - HYP_REST_ENDPOINT=http://vp0:7050
#  ports:
#    - "9090:9090"

#vp1:
#  extends:
#    file: compose-defaults.yml
#    service: vp
#  environment:
#    - CORE_PEER_ID=vp1
#    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
#    - CORE_SECURITY_ENROLLID=test_vp1
#    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
#  links:
#    - vp0
#    - membersrvc
#
#    activate for testing in a simulated bluemix blockchain service environment
#vp2:
#  extends:
#    file: compose-defaults.yml
#    service: vp
#  environment:
#    - CORE_PEER_ID=vp2
#    - CORE_PEER_DISCOVERY_ROOTNODE=vp1:7051
#    - CORE_SECURITY_ENROLLID=test_vp2
#    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
#  links:
#    - vp1
#    - membersrvc
#
#vp3:
#  extends:
#    file: compose-defaults.yml
#    service: vp
#  environment:
#    - CORE_PEER_ID=vp3
#    - CORE_PEER_DISCOVERY_ROOTNODE=vp2:7051
#    - CORE_SECURITY_ENROLLID=test_vp3
#    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
#  links:
#    - vp2
#    - membersrvc
